1120/full amounts in titles
gnosis/cowswap pull request #1166
Opened 2021-08-04 01:01 UTC by alfetopito

# Summary

Addressing comments https://github.com/gnosis/cowswap/pull/1127#pullrequestreview-718871330

"Titles, titles everywhere"

Impossible to screenshot all the titles at the same time, so just hover over any value in the UI.

1. On the swap page:
- Balances
- Send/Receive (buy/sell)
- Price
- [expert] Fees
- [expert] Minimum/maximum amounts

2. On the confirmation modal (not applicable on expert mode):
- From/to amounts
- Send/Receive amount (buy/sell)
- Price
- Fees
- Minimum/maximum amounts

  # To Test

1. On swap page with expert mode turned off, fill in all parameters.
2. Hover over every value from section `1` above
- [ ] Every section should display a title tooltip with the full amount of the respective field
3. Click on swap. Hover over every value from section `2` above
- [ ] On the confirmation modal, every section should display a title tooltilp with the full amount of the respective field
4. Repeat steps 1-3 for a buy order
- [ ] Result should be the same
5. Repeat steps 1-4 with the expert mode turned on

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2021-08-04 09:22 UTC, anxolin approved these changes
I think this PR is great!

Users hate rounding. Nice to see al my cents!

2021-08-04 09:51 UTC, MareenG requested changes
Great new feature. 
I checked it and it doesn't quite work as described in the instructions. 
On the Swap page it is shown for *Fees* and *Minimum/maximum amounts* when I am **not** in the expert mode and is disabled if I am in the expert mode. This should be the other way around right? 

Otherwise I was wondering why we don't show it on the swap page for the **from** and **to** amounts. It will be displayed in the confirmation modal but intuitively I also wanted to check those numbers on the swap page.

2021-08-04 10:12 UTC, biocom commented
Reviewed the tooltips. They work as mentioned. 

In my opinion they are ineffective as is, in terms of the general UX of using them. Reason for this is the fact we use the native browser tooltips (title="....."):
- There's a significant delay hovering, making it less pleasant to use IMO. 
- Aside from the delay, as a user you wont know they exist, only if you happen to hold your cursor for a longer period of time on the element.
- Lastly, this is a desktop only solution (what about mobile?) 

**Some ideas for alternatives:**
1. Use custom tooltips which show up quicker. But if we do so, I'd add some icon element for discoverability and to support mobile (touch -> icon).
2. Ditch the rounding in the swap container (primary purpose being a 'summary' of your trade) -> show full digits (with limitations?) on the confirmation modal -> expert mode has no rounding (with some limitations..)
3. Make it a toggle-able feature in settings -> Enable/Disable larger digits/decimals -> Expert mode has it **ON** by default.

I'd favor option 3 given I anticipate this being the preferred experience for *most* users, referring to how other DEX UI's integrate this. For expert/other users this could then be enabled.

2021-08-04 10:19 UTC, elena-zh commented
Tooltips work as described, but only for web version (as @biocom has just mentioned) 
Also, as @MareenG has mentioned, there are no tooltips for From/To fields values. 
Another thing is that tooltips may show a 'correct actual' value while UI shows too tiny amount..
![balance is greater](https://user-images.githubusercontent.com/70885163/128164925-27bddbf7-cdc3-41f3-85b4-46f6c9291b87.jpg)
![greater](https://user-images.githubusercontent.com/70885163/128164961-a65bfc76-9462-498e-8f06-a45466edee4a.jpg)

2021-08-04 14:46 UTC, biocom commented
@alfetopito As discussed, we probably go for tooltips, using our existing tooltip component with quicker hover feedback. Point of attention as you mentioned: conflict on mobile for the on click (switch price rate vs. showing tooltip).

2021-08-05 20:40 UTC, alfetopito commented
@MareenG & @elena-zh 

> On the Swap page it is shown for Fees and Minimum/maximum amounts when I am not in the expert mode and is disabled if 
> I am in the expert mode. This should be the other way around right?

I meant only on the expert mode because those fields are not visible on regular mode.
All fields visible and that make sense should have now a tooltip.
For regular mode, the fields in the red box will have a tooltip
![screenshot_2021-08-05_13-28-41](https://user-images.githubusercontent.com/43217/128417766-eb7a0d31-d670-47ff-adaf-f74709817c94.png)

Confirmation modal
![screenshot_2021-08-05_13-32-32](https://user-images.githubusercontent.com/43217/128417282-8aadf040-6186-41d4-8d5e-b90920a5d81a.png)
And finally expert mode
![screenshot_2021-08-05_13-35-16](https://user-images.githubusercontent.com/43217/128417556-1d456fe6-4e6a-4ab8-a2b7-80b90d478d86.png)

Note that USD estimations nor percentages have the tooltip.


> Tooltips work as described, but only for web version (as @biocom has just mentioned)

Correct, not visible in mobile version. I'll consider this with the feedback from Michel to be addressed in another PR.

> why we don't show it on the swap page for the from and to amounts
> Also, as @MareenG has mentioned, there are no tooltips for From/To fields values.

That is intended, as the user can see everything in the inputs by focusing in it and navigating using left/right arrow keys

> Another thing is that tooltips may show a 'correct actual' value while UI shows too tiny amount..

That has not been addressed yet, I'll deal with it in another PR

---

@biocom as discussed over the meeting, I won't add our fancy tooltips in this PR.
We can address that in a separated issue, as - given how complex it can get, thinking of all use cases and properly addressing mobile UX - this might take a long time and as of now it's already usable, although "hidden"

2021-08-06 08:36 UTC, elena-zh approved these changes
I created a separate issue #1188 for tooltips and mobile UX
As far as I understand, issues with amounts will be addressed in #1135

2021-08-06 08:37 UTC, merged