[Affiliate] Add FAQ
gnosis/cowswap pull request #1691
Opened 2021-10-25 18:07 UTC by alongoni

# Summary

Fixes #1683
Also Closed #1776 
Affiliate program information added to FAQ. [Source information.](https://docs.google.com/document/d/1BC66i33FT3eAK3o3B01uM7xDha9fJ1pvNN5TuBBzwCA/edit#heading=h.ca8szqjs3xd1)

![image](https://user-images.githubusercontent.com/622217/141137205-62ca6aad-0eac-457c-a694-38979ef5d4e4.png)
  # To Test

1. Open the [page `faq`](https://pr1691--gpswapui.review.gnosisdev.com/#/faq)

2021-11-10 15:18 UTC, elena-zh commented
Hey @alongoni , I have found that we have one question sounds a bit different than in the document
![name](https://user-images.githubusercontent.com/70885163/141140181-0fc2599f-3209-42b4-a8aa-fee1a191b0e7.jpg)

In addition, one question is missing there, but I'm not really sure whether it should present there...
![ьшыыштп](https://user-images.githubusercontent.com/70885163/141140244-52875a06-34dc-41f8-b3e9-b9b841242863.jpg)

2021-11-10 15:20 UTC, anxolin approved these changes
It looks great! 

As a nitipick, re-reading it, these 2 last questions feel a bit too long. Maybe theres ways to simplify
![image](https://user-images.githubusercontent.com/2352112/141140430-6e40b603-4ad0-48f9-9b25-ed8876139fef.png)

2021-11-10 15:22 UTC, alongoni commented
> Hey @alongoni , I have found that we have one question sounds a bit different than in the document ![name](https://user-images.githubusercontent.com/70885163/141140181-0fc2599f-3209-42b4-a8aa-fee1a191b0e7.jpg)
> 
I'll fix that.
> In addition, one question is missing there, but I'm not really sure whether it should present there... ![ьшыыштп](https://user-images.githubusercontent.com/70885163/141140244-52875a06-34dc-41f8-b3e9-b9b841242863.jpg)

This text is part of the [PR#1721](https://github.com/gnosis/cowswap/pull/1721)

2021-11-10 15:23 UTC, avsavsavs commented
@anxolin maybe one way to simplify the last two questions can simply just be merging them and getting rid of the question title for the last one.

2021-11-10 16:41 UTC, alfetopito requested changes

2021-11-10 16:41 UTC, alfetopito commented on src/custom/pages/Faq/index.tsx
> +            if you do so, you will also be able to see the # of trades and volume that your referral link gets credited
```suggestion
            if you do so, you will also be able to see the number of trades and volume that your referral link gets credited
```

2021-11-10 16:41 UTC, alfetopito commented on src/custom/pages/Faq/index.tsx
> +            the tracing, however, has already started.
```suggestion
            the tracking however, has already started.
```

2021-11-10 16:41 UTC, alfetopito commented on src/custom/pages/Faq/index.tsx
> +              entry Who can follow the referral link?).
Missing link to FAQ entry

2021-11-10 17:18 UTC, alfetopito reviewed
Changes look great!

One thing I just noticed, sorry about that

![Screenshot_20211110_091720](https://user-images.githubusercontent.com/43217/141161220-4eac8d75-c985-42e6-9bbe-6c4ccbbb0849.png)

Can you move the bottom of the previous sections to the new one so that text shows last in the page?

2021-11-10 19:35 UTC, alfetopito approved these changes

2021-11-10 19:54 UTC, merged

2021-11-11 08:37 UTC, elena-zh commented
LGTM!