applied 50% width
gnosis/cowswap pull request #1777
Opened 2021-11-04 12:08 UTC by maria-vslvn

# Summary

Fixes #1752 

Fields in sections do not have the same width. See the image:
![image](https://user-images.githubusercontent.com/25584298/140310738-58a9cc07-7000-4295-a175-afdfd6155809.png)

  # To Test

1. Open the page `Profile`
2. checkou items from the screenshot

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2021-11-04 12:34 UTC, elena-zh requested changes
Hey @maria-vslvn , great. 
But it would be ice to adjust fields better when a screen width is less than 350px. 
![less than 350](https://user-images.githubusercontent.com/70885163/140313793-c2ad5465-52fa-4690-a8bb-b5b6848f523b.jpg)

It would be nice not to move up the 'Total traded volume' icon, center-align the label's text and decrease a line-height

Also, it would be nice to use a line break for the 'Total traded volume' text even when a screen width is a bit more than 350 px in order to avoid situation, when visually elements seems to be not center-aligned
![avoid](https://user-images.githubusercontent.com/70885163/140314152-8f583633-09d9-42d6-810c-8d661a65a6aa.jpg)

2021-11-04 13:02 UTC, alongoni approved these changes
Looks great!

2021-11-04 19:26 UTC, alfetopito approved these changes
LGTM!

Just keep in mind it should be merged now onto `develop` branch instead of `release/1.4.0`

2021-11-05 09:13 UTC, elena-zh approved these changes

2021-11-08 21:02 UTC, alfetopito commented
I've rebased and changed the branch to point to develop. Will merge once build finished

2021-11-08 21:20 UTC, merged