fix for wallet change issue
gnosis/cowswap pull request #1921
Opened 2021-11-25 13:55 UTC by nenadV91

# Summary

Fixes #1909

Fix for the issue with changing wallets and the previous connection with WalletConnect is not saved

2021-11-25 15:35 UTC, elena-zh requested changes
Hi @nenadV91 !

The wallet is still appears disconnected when change accounts. See the video: connection is removed from the connected wallet as soon as I change a wallet. When I get back, I can see my previously connected wallet details, but I will not able to run a transaction
https://watch.screencastify.com/v/JpMBCqFM5sEhMfVvn7l3


I have also encountered a new issue: the app does not see that a wallet is disconnected after refreshing the page.  
Steps: 
1. Connect a WC wallet
2. Reload the page
3. Disconnect the app inside the connected wallet

For more details please see the video: https://watch.screencastify.com/v/dZeenarRgbaOugtKacI4

2021-11-25 15:48 UTC, elena-zh commented
@nenadV91 , the 2nd case I reported is not related to this PR: it is reproducible on Prod now. 
I created a separate issue for this case: #1923

2021-11-25 18:09 UTC, W3stside commented on src/custom/components/WalletModal/WalletModalMod.tsx
> +            setTimeout(() => localStorage.setItem(WALLET_CONNECT_STORAGE_KEY, tmpWCdata), 1500)
not in love with this but it does cover the issue.

i would open an issue with them and ask about:
1. a constructor param or sth allowing to set whether we want this storage wipe feature
2. them to fix their listeners .on('Web3ReactUpdate') to allow us to subscribe to changes there

2021-11-25 18:23 UTC, anxolin reviewed
Why this PR is using master as a base branch? 

If you are starting a hotfix, you should open a branch from master, and point this PR to this hotfix branch

2021-12-06 10:38 UTC, W3stside commented
@nenadV91 what's the status with this? last comment is 11 days ago. can we close?

2021-12-06 11:41 UTC, nenadV91 commented
@W3stside As we said on the sync this will not be implemented for now and I think we can close.

2022-01-20 18:10 UTC, anxolin commented
@nenadV91 i changed the base branch to `develop`, since this has been open for a bit. Whenever we resume this one, should be merged there

2022-03-15 12:32 UTC, closed without merging