Change typo
gnosis/cowswap pull request #1926
Opened 2021-11-25 19:45 UTC by anxolin

# Summary

<<if there's an issue>>Fixes #issueNumber

*High-level description of what your changes are accomplishing*

*Add screenshots if applicable. Images are nice :)*

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2021-11-26 16:22 UTC, alfetopito approved these changes

2021-11-29 11:12 UTC, W3stside commented on src/custom/pages/Faq/index.tsx
>              The affiliate program will initially run as a trial, and therefore there are currently no announced rewards,
This whole sentence is a bit weird.

```
The affiliate program will initially run as a trial and therefore there are currently no announced rewards. The tracking however, has already started.
```

2021-11-29 11:12 UTC, W3stside requested changes
wording change

2021-11-29 20:25 UTC, anxolin commented on src/custom/pages/Faq/index.tsx
>              The affiliate program will initially run as a trial, and therefore there are currently no announced rewards,
Applied!

2021-11-29 20:25 UTC, merged