Feature/1708 affiliate link owner info show
gnosis/cowswap pull request #2026
Opened 2021-12-21 01:04 UTC by maria-vslvn

# Summary

<<if there's an issue>>Fixes #1708 

add and modify the affiliate link owner info display ate the profile page

  # To Test

1. Open the page `Profile`
Checkout the new display and updates

2021-12-21 11:37 UTC, elena-zh requested changes
Hey @maria-vslvn , 

some issues: 
1. It would be nice to hide the field when a user is not connected to the Mainnet, as referral data is available only there
![mainnet](https://user-images.githubusercontent.com/70885163/146923406-a7f806d9-3274-4515-be8a-e2027c8974a3.jpg)

2. It would be great to hide the field if a user has not traded before
![do not show when no trades](https://user-images.githubusercontent.com/70885163/146923524-6f7ba5f3-69c2-4be3-87cb-4182c85e8312.jpg)

3. No need to show this link to a user with trades, and these trades were done without a referral link

4. Referral link can't be connected address. The value is the address that is uploaded to ipfs when a user follows a referral link

5. Seems that the fields are not placed in 1 horizontal line on the form
![not in line](https://user-images.githubusercontent.com/70885163/146923935-a534f67a-3c97-4a09-a06c-c9cb3b2a462e.jpg)

6. Mobile and tablet views are changed in this PR. It would be great to leave them as they are currently deployed in Prod
![mobile](https://user-images.githubusercontent.com/70885163/146924027-a37e22be-d78c-4e60-bee2-9f8e99b91703.jpg)
![tablet](https://user-images.githubusercontent.com/70885163/146924040-ff00a03d-d1f2-4e25-b5ef-d43b85873175.jpg)

2022-01-04 13:49 UTC, ramirotw commented
@maria-vslvn you should pick the referral address by using the hook `useReferralAddress`.

And btw there's a typo in `Reffered` -> `Referred`

2022-01-04 14:58 UTC, ramirotw approved these changes
👍

2022-01-04 18:09 UTC, alfetopito approved these changes
Minor comment, otherwise looking good to me.

Would just make sure Elena's comments are addressed

2022-01-04 18:09 UTC, alfetopito commented on src/custom/pages/Profile/index.tsx
> +import { shortenAddress } from '@src/utils'
Don't use `@src` imports.

Probably will work without it (I have not tested it)

```suggestion
import { shortenAddress } from 'utils'
```

2022-01-11 11:20 UTC, elena-zh commented
Hi @maria-vslvn , cases 1-4 from the comment above https://github.com/gnosis/cowswap/pull/2026#pullrequestreview-837335359 are still not fixed. 
The purpose of the current issue is to show a user an address he/she has followed, and under which he/she has done a trade. This value  (referral address) should be taken from the BE.
In this PR I see that you are trying to show the new referral link, that is currently active, and is stored in the local storage. 
I assume, that is why all these issues are still not fixed. 

Thanks.

2022-01-11 11:21 UTC, elena-zh requested changes
We still do not indicate under which link the 1st trade was done.

2022-02-11 14:38 UTC, matextrem commented
@ramirotw  @alfetopito  Which is the endpoint needed to retrieve the referrer user? `Trades` enpoint does not return any information related to that.

2022-02-11 15:00 UTC, ramirotw commented
> @ramirotw @alfetopito Which is the endpoint needed to retrieve the referrer user? `Trades` enpoint does not return any information related to that.

I believe the way we could do that is:
1. get the user first trade by using the /trades endpoint
2. using the orderId from that trade query the /orders/{uid}
3. using the appData from the order response, we could use the decode helper @alfetopito implemented in https://codepen.io/pacara/pen/BadZgjg (this should be part of the sdk btw)
4. extract the referrer address from there

does that makes sense @alfetopito or we have a simpler and better way to do it?

2022-02-11 15:23 UTC, alfetopito commented
> > @ramirotw @alfetopito Which is the endpoint needed to retrieve the referrer user? `Trades` enpoint does not return any information related to that.
> 
> I believe the way we could do that is:
> 
>     1. get the user first trade by using the /trades endpoint
> 
>     2. using the orderId from that trade query the /orders/{uid}
> 
>     3. using the appData from the order response, we could use the decode helper @alfetopito implemented in https://codepen.io/pacara/pen/BadZgjg (this should be part of the sdk btw)
> 
>     4. extract the referrer address from there
> 
> 
> does that makes sense @alfetopito or we have a simpler and better way to do it?

Yeah, that sounds about right.
Don't think there's an easier way right now.

2022-02-14 22:28 UTC, matextrem commented
I have read and agree to the CLA

2022-02-15 10:06 UTC, elena-zh commented
Hey @matextrem , not I can see a duplicating 'View all orders' link in any network when a user has trades. 
However, I can't see a referee data on the profile page
![image](https://user-images.githubusercontent.com/70885163/154039585-a723c5ff-5196-489a-9c64-fa6270f3c17d.png)

2022-02-15 13:42 UTC, matextrem commented
@elena-zh Removed one view all orders link

Regarding the other point, I can see it. Take into account that it will only shown once the referred address is fetched.

![image](https://user-images.githubusercontent.com/11525018/154073716-7872c63c-aef2-4a6e-b032-904b8a582999.png)

2022-02-15 15:43 UTC, elena-zh commented
Hey @matextrem , great!

The only thing I should notice that it would be nice to aggregate affiliate data for the referee for Barn and Prod environments and show it. I mean, this account on the image below has a referral link that was shared in Prod server. However, it is not displayed in the barn/dev environment 
![image](https://user-images.githubusercontent.com/70885163/154096192-54120fee-454b-4ada-9f55-54fb4994c4e5.png)
Account's trades: https://protocol-explorer.staging.gnosisdev.com/address/0xdEB73112e933b7e7E874BaBE33D2EbECc49f0514
Referral address: 0x6adE2eA11D5a119D8b431ef03DcD5401B733CEbe

Another my question is related to the mobile view: should we show this link above the section's title or we can move it down. @alongoni , WDYT?

2022-02-15 16:26 UTC, matextrem commented
Regarding the first point from Elena comment and talking to Rami, a solution for this would be trying to getTrades pointing to the default env (i.e: barn). If getTrades does not returns anything, try with prod environment.

WDTY is the best approach to handle it @alfetopito ?

CC: @ramirotw

2022-02-15 17:58 UTC, alongoni requested changes

2022-02-15 17:58 UTC, alongoni commented on src/custom/pages/Profile/index.tsx
> +              <FlexRow>
It should be like this (without adding extra space upper the Affiliate Program title)
![image](https://user-images.githubusercontent.com/622217/154120005-07a54659-3556-47ff-b555-3495e9c76c39.png)

2022-02-15 17:58 UTC, alongoni commented on src/custom/pages/Profile/index.tsx
> +              <FlexRow>
In mobile, I agree with Elena, we should list "Referred by: ... " below the "Las updated..." data.

2022-02-15 22:14 UTC, alongoni approved these changes
Looks great!
![image](https://user-images.githubusercontent.com/622217/154158492-4eb6690f-d2a8-454a-b977-89e36589d0e8.png)
![image](https://user-images.githubusercontent.com/622217/154158546-c7c5f306-22f6-4441-9039-fae30d668aba.png)

2022-02-15 23:00 UTC, alfetopito commented
> Regarding the first point from Elena comment and talking to Rami, a solution for this would be trying to getTrades pointing to the default env (i.e: barn). If getTrades does not returns anything, try with prod environment.
> 
> WDTY is the best approach to handle it @alfetopito ?
> 
> CC: @ramirotw

I was sure something like that had already been implemented for the affiliate program, before we upload it to IPFS, but looking at the code right now I couldn't find it.

Did we just talk about it but did not actually implement it?

Anyway, I think this would make sense for both but could be a follow up PR

2022-02-16 01:51 UTC, matextrem commented
@alfetopito You mean this ticket? https://github.com/gnosis/cowswap/issues/1819. @elena-zh shared it to me but I was unsure if it was the same case.

2022-02-17 22:52 UTC, alfetopito commented
@matextrem I've raised this internally with the backend team to check for an alternative solution.

Will let you know when I get an answer

2022-02-22 21:43 UTC, matextrem commented
@elena-zh @alfetopito updated!

2022-02-22 21:44 UTC, matextrem commented
I have read the CLA Document and I hereby sign the CLA

2022-02-22 21:44 UTC, matextrem commented
recheckcla

2022-02-23 10:43 UTC, elena-zh commented
Hey @matextrem , seems that the last your commit was not properly merged as I still can't see a referree for an account with trades in the Prod server
![image](https://user-images.githubusercontent.com/70885163/155303217-4177ccc1-4487-4487-9393-971a7cb79b47.png)
![image](https://user-images.githubusercontent.com/70885163/155303333-b79deeeb-6d39-4fdb-b2a0-a7ac427bc887.png)

@alongoni , WDYT about left-aligning all these elements in a mobile view like we do for the tablet view?
![image](https://user-images.githubusercontent.com/70885163/155303505-70e19a47-a8a9-4071-8315-2a5f6f6dcdaa.png)
![image](https://user-images.githubusercontent.com/70885163/155303548-a01136ca-8f08-41b5-ae0c-3c3248e81ea5.png)

Also, it would be nice to make have a common style:  currently, icons, fields' labels have different sizes, colors, etc.

2022-02-23 22:02 UTC, alfetopito commented on src/custom/api/gnosisProtocol/api.ts
> +    `https://api.cow.fi/${ChainId[chainId].toLowerCase()}/api`
Probably a const for each: 

```ts
const BARN_API_ENDPOINTS_PER_NETWORK: Record<ChainId, string> = {}
const PROD_API_ENDPOINTS_PER_NETWORK: Record<ChainId, string> = {}
```

2022-02-24 02:16 UTC, alongoni commented
Regarding styles:
![image](https://user-images.githubusercontent.com/622217/155443801-72045f20-c423-4cf1-8f02-762b230b0e7d.png)
@matextrem you can check the CSS here:
https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/?node-id=1759%3A2

Not sure yet about left-aligning all elements (Referred by + Last updated + View all orders). I'll check it in a prototype on figma.

2022-02-24 19:57 UTC, matextrem commented on src/custom/api/gnosisProtocol/api.ts
> +    const [stgResponse, prodResponse] = response
Worst case scenario, `stgResponse` and `prodResponse` would be `undefined`. They are validated later in the code so there wouldn't be any problem I think.

The thing is `Promise.allSettled` returns `PromiseSettledResult` which is not exported so you have to first filter by `fulfilled` in order to access to `value` key https://stackoverflow.com/a/67533949

2022-02-24 20:00 UTC, matextrem commented on src/custom/api/gnosisProtocol/api.ts
> +      const [stgErrResponse, prodErrResponse] = results as PromiseFulfilledResult<any>[]
There seems to be a problem with `Promise.allSettled `and typing (https://stackoverflow.com/a/67533949) . I tried the solution suggested there but I was not able to make it work with our current `eslint` configuration so I have to type those cases with `any`

2022-02-25 08:51 UTC, elena-zh commented
Hey @matextrem , great changes!

The last thing that I have noticed today is that the account referee info  is not auto-removed when switch to another account without trades/referral code. See the video: https://watch.screencastify.com/v/xHXmzYwUEKS80xTjMmWU

Could you please fix this?

2022-02-25 18:04 UTC, matextrem commented
@elena-zh Updated!

2022-02-28 15:44 UTC, elena-zh approved these changes
LGTM now!

2022-03-04 17:23 UTC, alfetopito commented
As was discussed in the last sync meeting, we decided to not proceed with this feature.

Thanks for the effort everyone, but unfortunately it won't go live.

2022-03-04 17:23 UTC, closed without merging