Profile} vCOW balance
gnosis/cowswap pull request #2051
Opened 2022-01-04 19:38 UTC by alongoni

# Summary

<<if there's an issue>>Fixes #issueNumber

*High-level description of what your changes are accomplishing*

*Add screenshots if applicable. Images are nice :)*

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2022-01-06 13:51 UTC, matextrem requested changes

2022-01-06 13:51 UTC, matextrem commented on src/custom/pages/Profile/index.tsx
Path should start from `components/`

2022-01-06 17:17 UTC, alfetopito commented
Tiny question: why the different font size on both sections?
![Screen Shot 2022-01-06 at 09 15 31](https://user-images.githubusercontent.com/43217/148423172-25a7d900-eb3e-47b7-8eac-3e4cab2746b0.png)

Although Profile is the page name, the two sections are equivalent IMO and should have the same font size on the headers

2022-01-06 17:17 UTC, alfetopito approved these changes
Other than the font size comment, looks good to me

2022-01-06 17:48 UTC, anxolin approved these changes
Looks ok to me, happy to merge this (or continue with the task of getting the real value and formatting the amount)

One minor concern to discuss with @michelbio is regarding the colors. I'm not sure the black background

One small thing we can do to make it look better imo is just use sth similar to what we used in the profile:
![image](https://user-images.githubusercontent.com/2352112/148427484-d0789554-caaa-4b31-b127-bc96d5ba902c.png)

2022-01-06 17:57 UTC, alongoni commented
> Tiny question: why the different font size on both sections? ![Screen Shot 2022-01-06 at 09 15 31](https://user-images.githubusercontent.com/43217/148423172-25a7d900-eb3e-47b7-8eac-3e4cab2746b0.png)
> 
> Although Profile is the page name, the two sections are equivalent IMO and should have the same font size on the headers

Good point. I was thinking we should have a main title as we have in other sections (e.g about, faqs). But anyway we can use the same font-size in both cases.

2022-01-06 18:11 UTC, alfetopito commented
> Looks ok to me, happy to merge this (or continue with the task of getting the real value and formatting the amount)
> 
> One minor concern to discuss with @michelbio is regarding the colors. I'm not sure the black background
> 
> One small thing we can do to make it look better imo is just use sth similar to what we used in the affiliate part: ![image](https://user-images.githubusercontent.com/2352112/148427484-d0789554-caaa-4b31-b127-bc96d5ba902c.png)

Indeed, we talked about this during the Protofire sync.
What we agreed on was to use the light/dark colors as a start, and iterate with Michel's input when he's back

But of course, open for feedback already

2022-01-07 13:06 UTC, matextrem approved these changes

2022-01-07 15:53 UTC, alongoni commented
> Looks ok to me, happy to merge this (or continue with the task of getting the real value and formatting the amount)
> 
> One minor concern to discuss with @michelbio is regarding the colors. I'm not sure the black background
> 
> One small thing we can do to make it look better imo is just use sth similar to what we used in the affiliate part: ![image](https://user-images.githubusercontent.com/2352112/148427484-d0789554-caaa-4b31-b127-bc96d5ba902c.png)

Hey @anxolin, thanks! Makes sense! Now we are using the same color than the affiliate section. It'll be changed when we have the dropdown working. 
![image](https://user-images.githubusercontent.com/622217/148569665-dd301a3b-c701-41b2-ae5d-9a3627c95807.png)

2022-01-07 17:00 UTC, merged