Add link read more in footer, and inform about changing networks
gnosis/cowswap pull request #2265
Opened 2022-01-23 18:49 UTC by anxolin

# Summary

Add the read more link below the button:
![image](https://user-images.githubusercontent.com/2352112/150693263-dd3f854f-e4ec-437f-ac6b-b605faaaacb4.png)

also here:
![image](https://user-images.githubusercontent.com/2352112/150693279-c08b74b5-540e-49f1-823d-22eba9b3490b.png)

Additionally, hint the user they might have a claiming available in another Network
![image](https://user-images.githubusercontent.com/2352112/150693311-a965df78-e5b5-432b-971b-c04ea75334df.png)

  # To Test

1. Make sure the new links work

2022-01-24 09:14 UTC, biocom commented
My first impression is, that the text link we use right below the primary button, is seen as a 'secondary' action. The 'Read more about vCOW' feels like it should be part of the description above instead.

2022-01-24 09:32 UTC, elena-zh commented
Links work for me!
However, I'd add a network name in the description as we do when search for a token in token lists: 
![image](https://user-images.githubusercontent.com/70885163/150756594-de4a17a0-3654-4b91-ae15-743a45199e72.png)
![image](https://user-images.githubusercontent.com/70885163/150756427-9452150f-1d00-4cb5-aee1-43a01a95b771.png)

2022-01-24 09:33 UTC, elena-zh approved these changes

2022-01-24 10:19 UTC, elena-zh requested changes
I noticed duplicating 'Read more' links on screens where Airdrop option is available to claim: 
![image](https://user-images.githubusercontent.com/70885163/150764740-b7b38bf8-abba-4f08-8aa0-a625b765f3a7.png)
It would be great to remove one of them.

2022-01-24 18:39 UTC, alfetopito commented on src/custom/pages/Claim/CanUserClaimMessage.tsx
> +          or try in a different network.
Agree with Elena, show what's the current network being checked

2022-01-24 19:55 UTC, anxolin commented
Added the network name
![image](https://user-images.githubusercontent.com/2352112/150854734-9def8a29-4639-4a32-a424-d722676d3b16.png)


Also remove the duplicated link

2022-01-24 19:56 UTC, anxolin commented
Please review in the consolidated version :)

2022-01-24 19:56 UTC, merged

2022-01-25 09:37 UTC, elena-zh commented
LGTM!

2022-01-25 11:30 UTC, W3stside commented
Approved

2022-01-25 13:20 UTC, biocom commented
Looks good. Two comments:
- We could later add a background color to the network name, using the same color as in the network switcher.
- Is it `...in {network}` or `...on {network}` ? For example: "Claims on Gnosis Chain".