[Technical Debt] Conditional logging
gnosis/cowswap pull request #2532
Opened 2022-03-09 14:06 UTC by W3stside

Part of #1887 - logging reduction

Create and use `dev<'Debug' | 'Log' | 'Info'>` instead of console equivalent, which only logs outside of `production` environment

Contains 3 non-custom changes: service-workers, service-workers-registration, and src/index (happy to discuss not doing this)

2022-03-09 16:28 UTC, elena-zh approved these changes

2022-03-09 18:23 UTC, alfetopito approved these changes

2022-03-10 17:58 UTC, anxolin requested changes
Why not doing a not so intrusive way, that also works nicely with libraries if they also log something

https://stackoverflow.com/questions/7042611/override-console-log-for-production

2022-03-14 15:50 UTC, W3stside commented
closing in favour of #2537

2022-03-14 15:50 UTC, closed without merging