Change warning on the profile page
gnosis/cowswap pull request #2556
Opened 2022-03-17 17:28 UTC by alongoni

# Summary

Fixes #2513 
![image](https://user-images.githubusercontent.com/622217/158859027-3e67060e-0023-441d-b33b-34cb4b6dfc40.png)
  # To Test

1. Connect to a wallet in Rinkeby/GC
2. Open Profile page
3. Check the warning message. Should say: '**Affiliate** data is only available for **Ethereum**. Please change the network to see it.'

2022-03-17 20:36 UTC, ramirotw requested changes

2022-03-17 20:36 UTC, ramirotw commented on src/hooks/useFetchListCallback.ts
> +        throw new Error('Could not construct Ethereum ENS resolver')
this isn't inside the `custom` folder and shouldn't be modified

2022-03-17 23:23 UTC, anxolin commented
I'm confused with the changes. Mainnet is the right name isn't it, or if we want to add Ethereum, would be Ethereum Mainnet. @elena-zh what is the reason to call it just "Ethereum"?

2022-03-18 08:27 UTC, elena-zh commented
@anxolin , this is due to we use 'Ethereum' in the network switcher. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1655e684-369a-4b13-a249-cc0f6c7ac451)
The same is on Explorer. 
So I thought we should be consistent with networks naming everywhere.

2022-03-18 08:38 UTC, elena-zh approved these changes
LGTM!

2022-03-18 10:42 UTC, ramirotw approved these changes

2022-03-18 11:00 UTC, merged

2022-03-29 08:17 UTC, anxolin commented
Good points Elena, yes we should be consistent