Claim vested COW for locked GNO
gnosis/cowswap pull request #2599
Opened 2022-03-28 13:24 UTC by jfschwarz

# Summary

This PR adds a section to the profile page for letting users claim vested COW tokens they received for locking GNO.

![image](https://user-images.githubusercontent.com/524089/160406448-9e295cfa-b2e0-4746-abf3-9162a0175c58.png)

# To Test

1. Open the page `Profile`
- [ ] If the connected account is eligible for vested COW from locked GNO (all addresses listed here: https://dune.xyz/bh2smith/Locked-GNO-Snapshot) it should show a section `COW vesting from locked GNO`
- [ ] The section should show the currently vested amount of tokens 
- [ ] Users that are not eligible should not see the section
2. Claim the vested COW
- [ ] Click the `Claim COW` button, sign the transaction
- [ ] A transaction shall be added to the pending list and the user shall be notified once it completes
- [ ] The claim button should be disabled and show `Successfully claimed`
- [ ] The vested amount field should update to show the balance that became vested since clicking the claim button

# Background

To prevent a negative impact on page load performance, the merkle proof data for claiming the vested tokens is fetched lazily, only for users that are eligible and only when navigating to the profile page. IMO this is a good trade-off between performance and simplicity. The gzipped claim data is 227kb for mainnet and 526kb for Gnosis Chain. Rolling out an API endpoint for fetching merkle proofs individually seems overkill.

2022-03-29 15:37 UTC, elena-zh commented
Hey @jfschwarz , great changes!
I'm able to see this section for accounts that have l locked GNO. 
However, I'd rather not to make so wide to keep the whole line. Maybe something like this 
![image](https://user-images.githubusercontent.com/70885163/160647771-6955dd84-d753-45eb-83fb-a1cf8b34a188.png)

Also, I was not able to Claim COW in Gnosis Chain due to this error: 
![revert GC](https://user-images.githubusercontent.com/70885163/160647897-8a16c6ee-fa8d-4fda-aa9f-99e07eb40391.jpg)

And I was not able to claim in the Mainnet due to I do not have an account (with a PK) that has locked GNO for claiming.

2022-03-29 15:52 UTC, anxolin reviewed
One quick feedback, which I was mentioning in slack. Do we really need to include these big JSON files? 

Ideally we would not include parts of the ABI that are not needed, or generate TS declarations for unused methods. 


Also, Im a bit concerned with adding these 2MB files for loading the profile. If you look how we did the airdrop in cowswap, we broke the big fat airdrop file into chunks, and we did a index for them. The index file will be small and will point to the chunk https://github.com/gnosis/cowswap/blob/b97055011dfc609bda856a5cba8ca8946e455f3e/src/custom/state/claim/hooks/index.ts#L817

2022-03-30 10:23 UTC, jfschwarz commented
> However, I'd rather not to make so wide to keep the whole line. 

@elena-zh That's a good point! I've now adjusted the flex layout so that only if there's an odd number of boxes, the last one will take the entire width.

As for the claiming, it's currently failing because the vesting contracts have not been funded with COW yet. So we must hold off releasing this PR until this has happened.

@anxolin I like the idea and have split up the merkle proof data into chunks. 👍

2022-03-30 14:40 UTC, elena-zh commented
@jfschwarz , thank you for improving the page layout! Looks much-much better!
But now I see always pending Claim card with this error in the console 
![image](https://user-images.githubusercontent.com/70885163/160861208-fa0f27b6-8cfe-414f-b228-8254ea028bfc.png)

The same is for GC: 
![image](https://user-images.githubusercontent.com/70885163/160861583-0f480f84-2fac-485d-957d-4f848013cd27.png)

Could you please fix it?

Thanks

2022-03-30 15:09 UTC, jfschwarz commented
@elena-zh Interesting... 🤔 It seems we found a bug in webpack/babel. The transpiration in the production build was wrong. I've found a way to work around this bug and it's working now.

2022-03-31 10:18 UTC, elena-zh commented
Hey @jfschwarz , great! Now I can send a TX to sign a transaction to the wallet. However, still I'm not able to test changes to the end (run and finish a transaction) due to I do not have personal accounts with locked GNO in any network. 

A new tiny issue I have found is related to a mobile/table views: sections content exceeds sections' height, so it would be great to fix this. 
![mobile view](https://user-images.githubusercontent.com/70885163/161032881-11ea4681-bba7-4808-bcfb-47987a7053ee.jpg)
 
Thank you!

2022-03-31 10:41 UTC, jfschwarz commented
Good catch, @elena-zh. fixed now ✔️

2022-03-31 11:12 UTC, elena-zh approved these changes
LGTM now!

2022-03-31 11:31 UTC, jfschwarz commented
The vesting contracts have been funded in the meanwhile, so this would be ready to be merged.

2022-03-31 13:42 UTC, fairlighteth commented
@elena-zh In terms of styling and responsive tests, approved. Thank you @jfschwarz !

2022-03-31 13:43 UTC, fairlighteth approved these changes
Approving based on styles/responsive tests.

2022-04-01 08:27 UTC, anxolin reviewed
Hi, thanks for splitting the files into chunks. Looks better!

In general in our team we usually refuse to review very big PRs. We believe in smaller PR are easier to review, therefore will get more assurances. This one still has 53K changes. I know most of it are the TS declarations and ABIs, but we usually try to do these ones as independent PRs, and even with these ones out of the way, this PR does many things.

In this case, we can make an exception though, although I would ask if we could not include the merkle data in our code. Instead we could load it from an external Gnosis repository. See how we didn't include even our claiming https://github.com/gnosis/cowswap/blob/b97055011dfc609bda856a5cba8ca8946e455f3e/src/custom/state/claim/hooks/index.ts#L70

One reason for this, is that this is a one-off thing that makes our git more heavy, and add too many files we won't need in the future. 

One additional nitpick, can you add SupportedChainId.MAINNET, etc instead of the hardcoded numbers for the network?

If you make this changes, with the noise out of the way, i can try to review the hooks and logic itself. 

BTW, I see you didn't use our logic for finding the chunk given an address and make your own, was it not possible to refactor/reuse?

2022-04-01 09:04 UTC, jfschwarz commented
> In this case, we can make an exception, although I would ask if we could not include the merkle data in our code. Instead we could load it from an external Gnosis repository.

Yes, I can move it to an external repo. The disadvantage of that approach is that I will have to manually implement fetch and caching rather than relying on webpack to handle chunk loading automatically, but sure I can do it. I see your point of keeping git light. 👍 

> BTW, I see you didn't use our logic for finding the chunk given an address and make your own, was it not possible to refactor/reuse?

The existing claim data fetching uses two requests: One fetching the index containing all addresses, a second one for fetching the chunk. Arguably, doing two http roundtrips might turn out to be slower than simply fetching the entire claim data in a single request. Therefore, I used the fact that the claim data is sorted to create an index that is so slim it can be bundled. If you wanna further optimize load performance you might wanna change the existing claim mechanism in the same way.

2022-04-01 11:15 UTC, W3stside requested changes
I will have to agree with @anxolin here and request changes. There's too much noise coming from this change and I don't believe the potential performance benefit warrants adding this much bulk to the app. Everything else looks great, thanks for the submission. Looking forward to seeing the changes and merging this in.

2022-04-01 11:15 UTC, W3stside commented on src/custom/pages/Profile/LockedGnoVesting/claimData/index.ts
> +import { SupportedChainId } from '@src/custom/constants/chains'
please change all paths prepended with `@src/custom/` to have it removed
e.g 
`@src/custom/abis/types` => `abis/types`
same if `./custom/*` => `*.ts` or equivalent. 
we have pathing aliases set up in tsconfig

2022-04-01 11:15 UTC, W3stside commented on src/custom/pages/Profile/LockedGnoVesting/hooks.ts
> +import { MerkleDrop, TokenDistro } from '@src/custom/abis/types'
i won't make more comments about the paths but there are other instances here

2022-04-01 11:15 UTC, W3stside commented on src/custom/pages/Profile/LockedGnoVesting/hooks.ts
> +  1: '0x68FFAaC7A431f276fe73604C127Bd78E49070c92',
please use our enum, `SupportedChainId` from the custom folder

2022-04-01 14:52 UTC, elena-zh commented
Hey @jfschwarz , I have noticed that:
1. when a user has vested COW  from locked GNO
2. and when a user presses on the 'Convert to COW' button to convert vCOW to COW

Then an incorrect 'waiting' modal appears: it says 'Claiming vested COW' instead of the 'Converting vCOW to COW' 

See the video: https://watch.screencastify.com/v/zPr5pm8QyM8AqkAabQ4i

So we need to separate these waiting modals: 
Convert: 
![convert](https://user-images.githubusercontent.com/70885163/161287937-6584a334-e20c-446b-bdf6-d498bbfc9ebd.jpg)

Claim vested: 
![image](https://user-images.githubusercontent.com/70885163/161288145-064c84cc-1eb2-4345-bce6-260567e1e15e.png)

Thanks!

2022-06-19 22:35 UTC, closed without merging