[Affiliate] Copy link component
gnosis/cowswap pull request #968
Opened 2021-07-18 23:16 UTC by matextrem

Summary
Closes #851 

Edit Copy component in order to allow copying a link either by clicking over the icon or address. 

As part of the discussion [here](https://github.com/gnosis/cowswap/pull/952#pullrequestreview-708958950) I decided to split this issues in 2 PRs (this is the one related to the implementation and then there will be another related to the integrations once the affiliate page is merged)

Testing steps
Since it is not a integration and given the fact we don't have Storybook to list components, there is no visual feedback until it is integrated into the affiliate page.

2021-07-19 14:19 UTC, ramirotw requested changes
Nice!

The `Copy.tsx` file is under the `AccountDetails` folder, not sure why.

Also, I'd remove the changes in the About page as they are not related.

2021-07-19 18:20 UTC, alfetopito requested changes
Tiny change regarding the `@src` path usage.

And I agree with Ramiro regarding the file location.
Think a best place would be `/src/custom/components/Copy/index.tsx`

2021-07-19 18:20 UTC, alfetopito commented on src/custom/components/AccountDetails/Copy.tsx
> +import useCopyClipboard from '@src/hooks/useCopyClipboard'
We prefer to use the `@src` reference only when required.
This should work with the default path.

I know this import comes automatically from VSCode, just keep an eye out :)

```suggestion
import useCopyClipboard from 'hooks/useCopyClipboard'
```

2021-07-19 18:20 UTC, alfetopito commented on src/custom/pages/About/index.tsx
> -
Don't think this change is needed

2021-07-19 18:30 UTC, matextrem commented
> Tiny change regarding the `@src` path usage.
> 
> And I agree with Ramiro regarding the file location.
> Think a best place would be `/src/custom/components/Copy/index.tsx`

I left the same location used for non custom components but I do agree is odd. I'll change it.

2021-07-19 19:54 UTC, alfetopito approved these changes

2021-07-21 09:29 UTC, ramirotw approved these changes

2021-07-21 09:41 UTC, merged